#!/bin/sh
set -eu
SOLUTION_ROOT=/solution
if [ ! -d "$SOLUTION_ROOT" ]; then SOLUTION_ROOT=/app/solution; fi
# Generated by batch_authoring_pass.py; solution files remain task-owned.
mkdir -p /app/engine/include/kay/render
cp -a "$SOLUTION_ROOT/engine/include/kay/render/graphics.h" /app/engine/include/kay/render/graphics.h
mkdir -p /app/engine/include/kay/scene
cp -a "$SOLUTION_ROOT/engine/include/kay/scene/scene.h" /app/engine/include/kay/scene/scene.h
mkdir -p /app/engine/src/render
cp -a "$SOLUTION_ROOT/engine/src/render/graphics.cpp" /app/engine/src/render/graphics.cpp
mkdir -p /app/engine/src/scene
cp -a "$SOLUTION_ROOT/engine/src/scene/scene.cpp" /app/engine/src/scene/scene.cpp
touch /app/.gfb_oracle_applied
