#!/bin/sh
set -eu
SOLUTION_ROOT=/solution
if [ ! -d "$SOLUTION_ROOT" ]; then SOLUTION_ROOT=/app/solution; fi
# Generated by batch_authoring_pass.py; solution files remain task-owned.
cp -a "$SOLUTION_ROOT/index.html" /app/index.html
mkdir -p /app/src
cp -a "$SOLUTION_ROOT/src/engine.js" /app/src/engine.js
mkdir -p /app/src
cp -a "$SOLUTION_ROOT/src/game.js" /app/src/game.js
mkdir -p /app/src
cp -a "$SOLUTION_ROOT/src/state.js" /app/src/state.js
