#!/bin/sh
set -eu
SOLUTION_ROOT=/solution
if [ ! -d "$SOLUTION_ROOT" ]; then SOLUTION_ROOT=/app/solution; fi
# Generated by batch_authoring_pass.py; solution files remain task-owned.
cp -a "$SOLUTION_ROOT/Main.tscn" /app/Main.tscn
mkdir -p /app/scripts
cp -a "$SOLUTION_ROOT/scripts/ink_sans_state.gd" /app/scripts/ink_sans_state.gd
