#!/bin/sh
set -eu
SOLUTION_ROOT=/solution
if [ ! -d "$SOLUTION_ROOT" ]; then SOLUTION_ROOT=/app/solution; fi
# Generated by batch_authoring_pass.py; solution files remain task-owned.
cp -a "$SOLUTION_ROOT/Main.tscn" /app/Main.tscn
mkdir -p /app/scripts
cp -a "$SOLUTION_ROOT/scripts/vehicle_effects.gd" /app/scripts/vehicle_effects.gd
cp -a "$SOLUTION_ROOT/tests" /app/tests
cp -a "$SOLUTION_ROOT/rubric.yaml" /app/rubric.yaml 2>/dev/null || cp -a /app/rubric.yaml /app/rubric.yaml
cp -a /app/tests /app/rubric.yaml /app/project.godot /app/task.toml /app/ 2>/dev/null || true
