#!/bin/sh
set -eu
SOLUTION_ROOT=/solution
if [ ! -d "$SOLUTION_ROOT" ]; then SOLUTION_ROOT=/app/solution; fi
# Generated by batch_authoring_pass.py; solution files remain task-owned.
mkdir -p /app/src/main/java/com/gameforge/localization
cp -a "$SOLUTION_ROOT/src/main/java/com/gameforge/localization/LocalizationPlugin.java" /app/src/main/java/com/gameforge/localization/LocalizationPlugin.java
mkdir -p /app/src/main/resources
cp -a "$SOLUTION_ROOT/src/main/resources/plugin.yml" /app/src/main/resources/plugin.yml
mkdir -p /app/src/main/resources/lang
cp -a "$SOLUTION_ROOT/src/main/resources/lang/en_us.properties" /app/src/main/resources/lang/en_us.properties
mkdir -p /app/src/main/resources/lang
cp -a "$SOLUTION_ROOT/src/main/resources/lang/ru_ru.properties" /app/src/main/resources/lang/ru_ru.properties
