#!/bin/sh
set -eu
SOLUTION_ROOT=/solution
if [ ! -d "$SOLUTION_ROOT" ]; then SOLUTION_ROOT=/app/solution; fi
# Generated by batch_authoring_pass.py; solution files remain task-owned.
cp -a "$SOLUTION_ROOT/Main.tscn" /app/Main.tscn
cp -a "$SOLUTION_ROOT/project.godot" /app/project.godot
mkdir -p /app/scripts
cp -a "$SOLUTION_ROOT/scripts/grenade_physics.gd" /app/scripts/grenade_physics.gd
mkdir -p /app/scripts
cp -a "$SOLUTION_ROOT/scripts/main.gd" /app/scripts/main.gd
